### ISSUE TITLE
Affine direct image 

### ISSUE THREAD

**Issue by zerotal** [Waerden001/Examples_and_Counterexamples_in_Elementary_Algebraic_Geometry#1]
In `Examples_and_Counterexamples_in_Elementary_Algebraic_Geometry/Basic_concepts/commutative_algebra.tex`, the section on affine direct images, one should add that F is a quasi-coherent sheaf, otherwise the assertion is not correct.

**Comment by Waerden001** [comment]
Have modified the file. Thanks, the great 鼎哥！

**Comment by Waerden001** [comment]
Solved.
